# Copyright (c) 2016-2018 ForgeRock AS. All rights reserved
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internship-pg
  template:
    metadata:
      labels:
        app: internship-pg
    spec:
      containers:
        - image: postgres:13
          name: internship-pg
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "300Mi"
          ports:
            - name: nodejs-port
              containerPort: 5432
          imagePullPolicy: Always
